### ISSUE TITLE
the jupyter notebook does not execute 

### ISSUE THREAD

**Issue by mcyhx** [untitled-ai/jupyter_ascending#30] opened 2021-11-18 12:12 UTC
After installing the package and following the simple example but stuck in the last step:
"python -m jupyter_ascending.requests.execute --filename example.sync.py --line 16" the jupyter notebook does not execute and directly create a new cell.

**Comment by mcyhx** [comment] 2021-12-12 03:12
I tested the **"execute_all"** command and it works. However, it does not execute the cell in the **"execute"** command and just inserts a new cell below. I examined the **execute_all.py** and **execute.py** and the **jsonrpcclient's request** function but did not find any clue that can cause this problem. I also reinstalled the jupyter notebook and  jupyter_ascending. The execute command doesn't execute. 
![test_jupyter_ascending](https://user-images.githubusercontent.com/31196373/145698740-bb2c63e9-f9b0-4235-9381-084dd2655fbd.png)

**Comment by dmalkr** [comment] 2022-03-15 05:05
Any progress for this issue?

**Comment by dmalkr** [comment] 2022-03-15 05:30
@mcyhx It seems index calculation is broken. In my next example, if you want to update line N, you need to call `execute` with `--line N-delta`. Let's consider code:

```python
# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.3.4
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %%
print("AAAAAAAAAAA") #line 16

# %%
print("XXXXXXXXXXX") # line 19

# %%
print("YYYYYYYYYYY") # line 22
```

So for update line 22 it is need to call `python -m jupyter_ascending.requests.execute --filename example.sync.py --line 17`

**Comment by zplizzi** [comment] 2022-12-22 20:11
I think this is a duplicate of #28, which is now fixed - let me know if not!

**Closed by zplizzi** 2022-12-22 20:11 UTC
