### ISSUE TITLE
Execute all works, but execute line does nothing

### ISSUE THREAD

**Issue by jmrussell** [untitled-ai/jupyter_ascending#38] opened 2022-06-17 04:45 UTC
Through both the plugin and through calling jupyter_ascending directly, I can run the code in all cells without issue, but when I try to send a specific line, it simply inserts a blank cell below it.

```
2022-06-16 23:43:42.510 | INFO     | jupyter_ascending.requests.sync:send:17 - Syncing File: /home/jr2396/example.sync.py...
2022-06-16 23:43:42.614 | INFO     | jupyter_ascending.requests.sync:send:26 - ... Complete
2022-06-16 23:43:42.616 | INFO     | __main__:send:59 - Sending request with ExecuteRequest(file_name='/home/jr2396/example.sync.py', cell_index=8, contents='')
2022-06-16 23:43:42.628 | INFO     | __main__:send:61 - ... Complete
```

**Comment by jmrussell** [comment] 2022-06-17 15:24
Line numbers are off by the length of the header in the .py file, so 13 in my case. Subtracting 13 from the current line and sending that works.

**Comment by monkeyxite** [comment] 2022-08-15 07:42
If you binding the notebook and py file via jupytext or simliar, disabling sync "include metadata" in jupytext would resolve this issue.

**Comment by zplizzi** [comment] 2022-12-22 20:11
I think this is a duplicate of #28, which is now fixed - let me know if not!

**Closed by zplizzi** 2022-12-22 20:11 UTC
